# This is a basic workflow to help you get started with Actions

name: DIY ImmortalWrt

# Controls when the workflow will run

on:
  workflow_dispatch:
    inputs:
      release:
        description: "上传到 Release"
        required: false
        default: 'false'
      upload-all:
        description: "上传到 Artifacts"
        required: false
        default: 'true'
      model:
        description: '机型,平台'
        required: false
        default: 'qihoo_360t7-ubootmod,mediatek/filogic'

env:
  DOWNLOAD_BASE: https://downloads.immortalwrt.org
  VENDOR: immortalwrt
  VERSION: 23.05.3
  DATETIME: ''
  PLATFORM: ''
  URL_PLATFORM: ''
  MODEL: ''
  DATE: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# 该工作流程包含一个名为“build”的作业 
 build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 初始化环境
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip qemu-utils mkisofs jq
      
      - name: 设置环境变量
        run: |
          echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          
          # 使用逗号作为分隔符分割字符串
          IFS=',' read -r model platform <<< "${{ github.event.inputs.model }}"
          
          # 将分割得到的值赋给对应的环境变量
          echo "MODEL=$model" >> $GITHUB_ENV
          
          # 不要覆盖原本的 platform，因为我们将在下一步中使用它
          echo "URL_PLATFORM=$platform" >> $GITHUB_ENV
          
          # 从环境变量中读取 platform 的值，并替换 / 为 -
          PLATFORM=$(echo "$platform" | tr '/' '-')
          echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
          
      # 在 $GITHUB_WORKSPACE 下签出您的存储库，以便您的作业可以访问它
      - name: 查看
        uses: actions/checkout@v3
        with: 
          path: origin

      - name: 下载imagebuilder
        run: |
          wget $DOWNLOAD_BASE/releases/$VERSION/targets/${{ env.URL_PLATFORM }}/$VENDOR-imagebuilder-$VERSION-${{ env.PLATFORM }}.Linux-x86_64.tar.xz
          tar -xvf $VENDOR-imagebuilder-$VERSION-${{ env.PLATFORM }}.Linux-x86_64.tar.xz
          rm -rf $VENDOR-imagebuilder-$VERSION-${{ env.PLATFORM }}.Linux-x86_64.tar.xz
          cp -r $GITHUB_WORKSPACE/origin/* $GITHUB_WORKSPACE/$VENDOR-imagebuilder-$VERSION-${{ env.PLATFORM }}.Linux-x86_64/
      
      # - name: 下载外部包
      #   working-directory: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-${{ env.PLATFORM }}.Linux-x86_64
      #   run: |
      #     cat external-package-urls.txt | xargs wget -P packages  

      - name: 批量下载包
        working-directory: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-${{ env.PLATFORM }}.Linux-x86_64
        run: |
          bash scripts/download-packages.sh

      - name: 运行补丁和 DIY 脚本
        working-directory: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-${{ env.PLATFORM }}.Linux-x86_64
        run: |
          bash scripts/builder-patch.sh

      - name: 生成固件
        working-directory: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-${{ env.PLATFORM }}.Linux-x86_64
        run: |
          bash scripts/build.sh

      - name: 上传 VDI 映像用于开发目的
        if: github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.VENDOR }}-${{ env.VERSION }}-x86_64-vdi-image-${{ env.DATETIME }}
          path: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-${{ env.PLATFORM }}.Linux-x86_64/bin/targets/${{env.URL_PLATFORM}}/*.vdi

      - name: 将所有固件上传到 Artifacts
        if: github.event.inputs.upload-all == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.VENDOR }}-${{ env.VERSION }}-${{ env.MODEL }}-images-${{ env.DATETIME }}
          path: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-${{ env.PLATFORM }}.Linux-x86_64/bin/targets/${{env.URL_PLATFORM}}/*

      - name: 上传固件发布
        if: github.event.inputs.release == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-${{ env.PLATFORM }}.Linux-x86_64/bin/targets/${{env.URL_PLATFORM}}/*
          asset_name: ${{ github.event.repository.name }}-${{ github.sha }}
          tag: release-${{ env.DATE }}
          overwrite: true
