name: Fuzzy Search Devices

on:
  workflow_dispatch:
    inputs:
      query:
        description: "搜索关键词"
        required: true
        default: "360t7"

jobs:
  fuzzy_search:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install jq

    - name: Run fuzzy search script
      id: fuzzy_search
      run: |
        echo ${{ github.event.inputs.query }}
        result=$(jq --arg query "${{ github.event.inputs.query }}" \
          '.[] | select(.supportedDevices | map(select(test($query))) | length > 0).name' router_configs.json)
        echo "Result: $result"
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: Print results
      run: |
        echo "Matched device: ${{ steps.fuzzy_search.outputs.result }}"